name: al9
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  schedule:
    - cron: '1 9 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge -y needrestart || true
          sudo apt install -y bash wget curl openssl
          sudo ln -svf bash /bin/sh
          sudo /bin/rm -fr /tmp/*
          sudo rm -fr /usr/local/lib/android/ /usr/lib/google-cloud* /usr/bin/gcloud*  /usr/share/man/man1/gcloud* /usr/share/doc/google-cloud* /usr/share/google-cloud*
          sudo systemctl start docker
          sudo df -Th

      - name: al9
        run: sudo /bin/bash run-build-al9.sh

      - name: Generate release tag env
        run: |
          _release_ver="$(ls -1 /tmp/_output_assets/_output/ | sed 's|.*rust-v||g; s|-stable.*||g' | tail -n 1)"
          echo "_release_ver=${_release_ver}" >> $GITHUB_ENV

      - name: Upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env._release_ver }}
          files: /tmp/_output_assets/_output/rust*.tar*
          overwrite_files: true

      - name: Delete
        run: |
          sed -e "/^_release_ver=/d" -i $GITHUB_ENV
          sudo rm -fr /tmp/_output_assets
